-- Production security upgrade for Plant Zone POS.
-- Run this after you move users to Supabase Auth.
-- Important: this locks app_state to authenticated users only.

create type public.app_role as enum ('admin', 'inventory_manager', 'staff');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  username text not null unique,
  role public.app_role not null default 'staff',
  can_view_reports boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'System',
  action text not null,
  target text,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_history (
  id bigint generated by default as identity primary key,
  plant_id text,
  plant_name text not null,
  plant_code text,
  before_quantity integer not null check (before_quantity >= 0),
  after_quantity integer not null check (after_quantity >= 0),
  reason text not null,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'System',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;
alter table public.inventory_history enable row level security;
alter table public.app_state enable row level security;

create or replace function public.current_app_role()
returns public.app_role
language sql
security definer
set search_path = public
stable
as $$
  select role from public.profiles where id = auth.uid() and active = true
$$;

drop policy if exists "Plant Zone app can read state" on public.app_state;
drop policy if exists "Plant Zone app can insert state" on public.app_state;
drop policy if exists "Plant Zone app can update state" on public.app_state;

create policy "Authenticated users can read app state"
on public.app_state
for select
to authenticated
using (public.current_app_role() is not null);

create policy "Managers can insert app state"
on public.app_state
for insert
to authenticated
with check (public.current_app_role() in ('admin', 'inventory_manager'));

create policy "Managers can update app state"
on public.app_state
for update
to authenticated
using (public.current_app_role() in ('admin', 'inventory_manager'))
with check (public.current_app_role() in ('admin', 'inventory_manager'));

create policy "Users can read their own profile"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.current_app_role() = 'admin');

create policy "Admins manage profiles"
on public.profiles
for all
to authenticated
using (public.current_app_role() = 'admin')
with check (public.current_app_role() = 'admin');

create policy "Admins read audit logs"
on public.audit_logs
for select
to authenticated
using (public.current_app_role() = 'admin');

create policy "Authenticated users create audit logs"
on public.audit_logs
for insert
to authenticated
with check (actor_id = auth.uid() or actor_id is null);

create policy "Managers read inventory history"
on public.inventory_history
for select
to authenticated
using (public.current_app_role() in ('admin', 'inventory_manager'));

create policy "Managers create inventory history"
on public.inventory_history
for insert
to authenticated
with check (public.current_app_role() in ('admin', 'inventory_manager'));
